### ISSUE TITLE
Crash when mouse is moved

### ISSUE THREAD

**Issue by zaknafean** [tlitookilakin/message_box#1]
Using Godot 3.2.3

**event.echo** crashes when _InputEventMouseMotion_ occurs as shown in the attached screen shot.  

I assume the goal is to filter out unnecessary events, but perhaps adding or event is InputEventMouseMotion could fix the issue.
edit: Seems to crash on InputEventMouseButton too.
```
	if _tween == null or event is InputEventMouseMotion or event.echo:
		return
```

![error](https://user-images.githubusercontent.com/7741797/94326888-57f2ae00-ff75-11ea-8a3d-7d0b209c4120.png)

**Comment by ThatMaidGuy** [comment]
I also encountered this problem. Fixed by replace `event.echo` to `event.is_echo()`

**Comment by zaknafean** [comment]
Investigating further, the code works fine if something else is intercepting the mouse events first. If not though, the crash is pretty consistent, but WeatleyHDDs fix seems to fix it very well.

**Comment by tlitookilakin** [comment]
thanks for the heads-up! Something must have changed in .2.3, I'll take a look and fix it.

EDIT: and the reason it doesn't crash if something else handles it is because it's only reading unhandled input instead of raw input, so that makes sense.

**Comment by tlitookilakin** [comment]
Should be fixed now. it looks like they just changed how some stuff worked.
