### ISSUE TITLE
Auto scroll doesn't work

### ISSUE THREAD

**Issue by zaknafean** [tlitookilakin/message_box#2]
Using Godot 3.2.3

The auto scroll functionality seems to be broken, or at least your implementation is depending on something that may be bugged.

As the screen show below shows, no options are checked that should be interfering, however you can see in the console output, that get_visible_line_count() is never greater than 0. This apparently is a known issue and has a fix slated for the 4.0 release as shown here: 
https://github.com/godotengine/godot/pull/40217

I'm not sure if there is a workaround that can be used in the mean time, but this is probably something worth noting.

![image](https://user-images.githubusercontent.com/7741797/94341516-ed268e80-ffd7-11ea-9c1b-b0ca5524e982.png)

**Comment by tlitookilakin** [comment]
hmmm
I haven't updated to .2.3 so I'll do that and take a look and see if I can figure out what is happening. The code is already using some hacky workarounds, so chances are they fixed some bugs and it broke the patch.

**Comment by tlitookilakin** [comment]
I'm testing it on godot 3.2.3 and it seems to work just fine, as before. can you please provide a test project so I can replicate the bug?

Actually, it may just be an issue with visible_line_count. For whatever reason it works fine for me, which may be why I can't replicate the bug. I'll see what I can do to avoid using visible_line_count.

**Comment by tlitookilakin** [comment]
it may also be related to this issue: https://github.com/godotengine/godot/issues/40982

So I will be busy for a few days, but my current plan for patching this will be to add an alternate, less-accurate autoscroll that can be enabled or disabled via node settings. Update should be released by the end of next week

**Comment by zaknafean** [comment]
I'll get a minimal recreation of the bug uploaded sometime today. Thanks for looking into it.

**Comment by tlitookilakin** [comment]
The most recent commit adds an alternate scroll option. Would you mind giving it a spin to check for issues before I upload it to the asset library? (You will need to check "Use Alt Scroll" in the inspector to enable the alternate autoscroll)

This doesn't FIX the broken thing but it adds a different method that doesn't rely on it.

**Comment by zaknafean** [comment]
With pleasure. Will report back asap

**Comment by zaknafean** [comment]
For whatever my usecase was, it worked perfectly. 

The funny thing is I use the message box in other places, and it works just fine, but as part of this scene I built, the scroll just fails. So strange. I attached a copy of my project that fails to scroll without  your new fix, just in case you can find some use for it. But otherwise with the work around I suppose this issue is closed!

Thanks for the hard work.

[TestForMessageBox.zip](https://github.com/tlitookilakin/message_box/files/5302246/TestForMessageBox.zip)

**Comment by tlitookilakin** [comment]
Thanks for checking! The update is on its way to the asset library now.
