### ISSUE TITLE
Does not autoplay with message is changed

### ISSUE THREAD

**Issue by lgmeister** [tlitookilakin/message_box#3]
I'm using set_text to change the dialog in a message box but when I do so, it changes the text without any typewriter animation. It just instantly puts the text up.

**Comment by tlitookilakin** [comment]
don't use set_text, that is not supported, just directly change the `message` variable.

**Comment by tlitookilakin** [comment]
see the [usage docs](https://github.com/tlitookilakin/message_box/wiki/Usage) for details on how to use it.

**Comment by lgmeister** [comment]
Thank you! I feel dumb now. I didn't understand that message was an inherent function.

**Comment by tlitookilakin** [comment]
absolutely! To be honest, I only have it written that way because godot 3.2 doesn't allow you to properly override inherited properties and methods. When 4.0 gets a stable release I will be able to streamline a lot of stuff and hopefully things will make a little more sense.
